env:
  es6: true
  node: true

extends:
  - google
  - plugin:eslint-plugin-import/errors
  - plugin:eslint-plugin-import/warnings
  - plugin:eslint-plugin-import/typescript

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module

plugins:
  - "@typescript-eslint"
  - "import"

ignorePatterns:
  - '*.d.ts'

rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^[_]+$"
      argsIgnorePattern: "^[_]+$"
      ignoreRestSiblings: true

  # Needs to disable local no-unused-vars for this rule to work properly
  no-unused-vars:
    - off

  "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
        - TSTypeParameterInstantiation
      MemberExpression: 1

  # Needs to disable local indent for this rule to work properly
  indent:
    - off

  linebreak-style:
    - error
    - unix

  max-len:
    - error
    - code: 119

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  import/newline-after-import:
    - error
    - count: 2

  import/no-unresolved:
    - error

  object-curly-spacing: off

  "@typescript-eslint/object-curly-spacing":
    - error
    - never

  semi:
    - off

  "@typescript-eslint/semi":
    - error

  space-in-parens:
    - error
    - never

settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx

  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - spinach-nft-server
        - spinach-nft-common
