env:
  es6: true
  node: true

extends:
  - google
  - plugin:eslint-plugin-import/errors
  - plugin:eslint-plugin-import/warnings
  - plugin:eslint-plugin-import/typescript

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module

plugins:
  - "@typescript-eslint"
  - "import"
  - unused-imports

ignorePatterns:
  - '*.d.ts'

rules:
  # Need to disable this for `unused-imports/no-unused-vars` to work properly
  no-unused-vars:
    - off

  # Need to disable this for `unused-imports/no-unused-vars` to work properly
  "@typescript-eslint/no-unused-vars":
    - off

  unused-imports/no-unused-vars:
    - error
    - varsIgnorePattern: "^[_]+$"
      argsIgnorePattern: "^[_]+$"
      ignoreRestSiblings: true

  unused-imports/no-unused-imports:
    - error

  "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
        - TSTypeParameterInstantiation
      MemberExpression: 1

  # Needs to disable local indent for this rule to work properly
  indent:
    - off

  linebreak-style:
    - error
    - unix

  max-len:
    - error
    - code: 119

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  import/newline-after-import:
    - error
    - count: 2

  import/no-relative-packages:
    - error

  import/no-unresolved:
    - error

  object-curly-spacing: off

  no-restricted-imports:
    - error
    - patterns:
        - 'spinach-nft-*'

  padding-line-between-statements:
    - error
    - blankLine: always
      prev: "*"
      next: cjs-export
    - blankLine: always
      prev: "*"
      next: export
    - blankLine: always
      prev: const
      next: cjs-export
    - blankLine: always
      prev: "*"
      next: export

  "@typescript-eslint/object-curly-spacing":
    - error
    - never

  semi:
    - off

  "@typescript-eslint/semi":
    - error

  comma-dangle:
    - off

  "@typescript-eslint/comma-dangle":
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
      tuples: always-multiline
      enums: always-multiline
      generics: ignore

  space-in-parens:
    - error
    - never

settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx

  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - spinach-nft-server
        - spinach-nft-common
