pool:
  vmImage: windows-latest

variables:
  - template: variables/main.yml
  - template: variables/checkout-and-cache.yml

trigger:
  paths:
    include:
      - spinach-nft-common/*
      - spinach-nft-ui/*

stages:
- stage: Lint

  jobs:
    - job: Lint

      steps:
      - template: templates/checkout-and-cache.yml

      - script: yarn run lint
        displayName: 'Lint Source'
        workingDirectory: ./$(APP_FOLDER_NAME)

      - script: yarn run lint:css
        displayName: 'Lint CSS'
        workingDirectory: ./$(APP_FOLDER_NAME)

      - script: yarn run g:devops
        displayName: 'Report Failure'
        condition: failed()
        env:
          AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
          AZ_DEVOPS_TITLE: $(Build.DefinitionName) - $(Build.BuildNumber)
          AZ_DEVOPS_STATUS: $(Agent.JobStatus)
          AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)

- stage: BuildDeploy
  displayName: Build & Deploy

  jobs:
    - job: Build
      strategy:
        matrix:
          Main:
            NEXT_PUBLIC_HOST: 'https://tg8888.net'
            NEXT_PUBLIC_SERVER_API: 'https://server.tg8888.net'
            ENVIRONMENT: 'main'
          Backup:
            NEXT_PUBLIC_HOST: 'https://tg5888.net'
            NEXT_PUBLIC_SERVER_API: 'https://server.tg5888.net'
            ENVIRONMENT: 'backup'
        maxParallel: 2

      steps:
        - template: templates/checkout-and-cache.yml

        - script: yarn run build
          displayName: 'Build App'
          workingDirectory: ./$(APP_FOLDER_NAME)
          env:
            CI: 1
            NODE_ENV: production
            MONGODB_URI: $(MONGODB_URI)
            AZURE_BLOB_URI: $(AZURE_BLOB_URI)

        - template: templates/copy-dependencies.yml

        - task: ArchiveFiles@2
          displayName: 'Archive Build'

          inputs:
            rootFolderOrFile: ./$(APP_FOLDER_NAME)
            includeRootFolder: false
            archiveType: 'tar'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'

          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            ArtifactName: '$(APP_FOLDER_NAME)-artifact-$(ENVIRONMENT)'
            publishLocation: 'Container'

        - script: yarn run g:devops
          displayName: 'Report DevOps Result'
          condition: always()
          env:
            AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
            AZ_DEVOPS_TITLE: $(Build.DefinitionName) - $(Build.BuildNumber) ($(ENVIRONMENT))
            AZ_DEVOPS_STATUS: $(Agent.JobStatus)
            AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
